export function renderAdminPage(): string {
  return `<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>WhatsApp Codex Nexo</title>
<style>
:root{font-family:Inter,system-ui,sans-serif;color-scheme:dark;--bg:#0b0d10;--panel:#14171c;--line:#2a3038;--muted:#949ca8;--good:#54d68a;--warn:#efbf52;--bad:#ff7373}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#f5f7fa}.page{width:min(1080px,calc(100% - 32px));margin:auto;padding:40px 0 80px}h1{font-size:clamp(36px,6vw,64px);letter-spacing:-.05em;margin:8px 0}.lead{color:var(--muted);max-width:760px;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:14px;margin-top:22px}.card{grid-column:span 6;background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:18px}.wide{grid-column:1/-1}.row{display:flex;gap:10px;align-items:center;justify-content:space-between;flex-wrap:wrap}.cluster{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.badge{border:1px solid var(--line);border-radius:999px;padding:5px 9px;font-size:12px;color:var(--muted)}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--warn);margin-right:6px}.dot.open{background:var(--good)}.dot.error,.dot.logged_out{background:var(--bad)}button,input,select{font:inherit}button{border:1px solid var(--line);border-radius:10px;padding:9px 12px;background:#1c2128;color:#fff;font-weight:700;cursor:pointer}button.primary{background:#f5f7fa;color:#0b0d10}button.danger{color:var(--bad);background:transparent}button:disabled{opacity:.5}input,select{width:100%;background:#0f1216;color:#fff;border:1px solid var(--line);border-radius:10px;padding:10px}.fields{display:grid;grid-template-columns:2fr 1fr auto;gap:8px;align-items:end}.muted{color:var(--muted)}.small{font-size:12px}.qr{background:#fff;border-radius:14px;padding:12px;width:min(340px,100%);margin-top:14px}.qr img{display:block;width:100%}.list{display:grid;gap:10px;margin-top:12px}.message{padding:10px 0;border-top:1px solid var(--line)}.message:first-child{border-top:0}.text{white-space:pre-wrap;overflow-wrap:anywhere;margin-top:4px}.status{min-height:20px;margin-top:8px}.error{color:var(--bad)}code{font-family:ui-monospace,monospace}@media(max-width:760px){.card{grid-column:1/-1}.fields{grid-template-columns:1fr}.page{padding-top:24px}}
</style>
</head>
<body><main class="page">
<div class="small muted">CODEX NEXO · WHATSAPP</div>
<h1>WhatsApp bridge.</h1>
<p class="lead">Varias cuentas de entrada observadas y una sola cuenta de salida para Codex. Las cuentas input nunca envían; la cuenta output nunca entra al archivo de búsqueda.</p>
<div id="app"><div class="card wide muted">Cargando…</div></div>
</main>
<script>
const app=document.getElementById('app');
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]));
async function api(path,o={}){const r=await fetch(path,{cache:'no-store',...o});let b={};try{b=await r.json()}catch{}return{r,b}}
function roleLabel(r){return r==='output'?'OUTPUT · Codex':'INPUT · observado'}
function accountCard(a){const rt=a.runtime||{state:'idle'};return '<article class="card"><div class="row"><div><strong>'+esc(a.label)+'</strong><div class="small muted" style="margin-top:4px">'+roleLabel(a.role)+(a.phoneJid?' · '+esc(a.phoneJid):'')+'</div></div><span class="badge"><span class="dot '+esc(rt.state)+'"></span>'+esc(rt.state)+'</span></div>'+(rt.lastError?'<div class="error small" style="margin-top:10px">'+esc(rt.lastError)+'</div>':'')+(rt.qrDataUrl?'<div class="qr"><img src="'+esc(rt.qrDataUrl)+'" alt="QR WhatsApp"><div style="color:#111;text-align:center;font-weight:700;margin-top:6px">WhatsApp → Dispositivos vinculados</div></div>':'')+'<div class="cluster" style="margin-top:14px"><button data-connect="'+esc(a.id)+'">'+(rt.state==='open'?'Reiniciar':'Conectar / QR')+'</button><button class="danger" data-delete="'+esc(a.id)+'">Desvincular y borrar cuenta</button></div><div class="small muted" style="margin-top:10px">recibidos '+Number(rt.receivedMessages||0)+' · guardados '+Number(rt.storedMessages||0)+' · historial '+Number(rt.historyMessages||0)+'</div></article>'}
function render(state){const accounts=state.accounts||[],hasOutput=accounts.some(a=>a.role==='output');app.innerHTML='<div class="grid"><section class="card wide"><div class="row"><div><strong>Agregar cuenta</strong><div class="small muted">Podés crear todos los inputs que quieras; output está limitado a uno. Al crearla, Nexo inicia automáticamente la vinculación y muestra el QR.</div></div></div><form id="add" class="fields" style="margin-top:12px"><input name="label" placeholder="Ej: WhatsApp Diego" required maxlength="120"><select name="role"><option value="input">Input</option><option value="output" '+(hasOutput?'disabled':'')+'>Output de Codex</option></select><button class="primary">Crear y vincular</button></form><div id="addst" class="status small"></div></section>'+accounts.map(accountCard).join('')+'<section class="card wide"><div class="row"><div><strong>Buscar en inputs</strong><div class="small muted">Busca texto, nombre del chat, remitente y cuenta.</div></div></div><div class="cluster" style="margin-top:12px"><input id="q" placeholder="Ej: Juan bomba" style="max-width:420px"><button id="search">Buscar</button><button id="recent">Recientes</button></div><div id="results" class="list"></div></section>'+(hasOutput?'<section class="card wide"><strong>Probar output</strong><p class="small muted">Sólo para diagnóstico local. El MCP usa exactamente el mismo canal.</p><div class="fields"><input id="to" placeholder="549... o JID"><input id="msg" placeholder="Mensaje"><button id="send">Enviar</button></div><div id="sendst" class="status small"></div></section>':'')+'</div>';bind()}
function showMessages(messages){const slot=document.getElementById('results');slot.innerHTML=(messages||[]).length?(messages||[]).map(m=>'<div class="message"><div class="small muted">'+esc(new Date(m.occurredAt).toLocaleString())+' · '+esc(m.accountLabel)+' · '+esc(m.chatName||m.chatJid)+(m.senderName?' · '+esc(m.senderName):'')+'</div><div class="text">'+esc(m.text||'['+(m.messageType||'mensaje sin texto')+']')+'</div></div>').join(''):'<div class="muted small">Sin resultados.</div>'}
function bind(){document.getElementById('add').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),st=document.getElementById('addst');st.className='status small';st.textContent='Creando cuenta…';const out=await api('/api/accounts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({label:fd.get('label'),role:fd.get('role')})});if(!out.r.ok){st.className='status small error';st.textContent=out.b.error||'Error';return}st.textContent='Iniciando vínculo con WhatsApp…';const connect=await api('/api/accounts/'+encodeURIComponent(out.b.id)+'/connect',{method:'POST'});if(!connect.r.ok){st.className='status small error';st.textContent=connect.b.error||'No se pudo iniciar la vinculación';await load();return}await load()};document.querySelectorAll('[data-connect]').forEach(b=>b.onclick=async()=>{b.disabled=true;const card=b.closest('.card'),open=card.querySelector('.badge')?.textContent?.includes('open');const out=await api('/api/accounts/'+encodeURIComponent(b.dataset.connect)+'/'+(open?'restart':'connect'),{method:'POST'});if(!out.r.ok)alert(out.b.error||'Error');await load()});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Esto desvincula WhatsApp, borra las credenciales locales y elimina el archivo de mensajes guardados de esta cuenta. ¿Continuar?'))return;const out=await api('/api/accounts/'+encodeURIComponent(b.dataset.delete)+'/logout',{method:'POST'});if(!out.r.ok)alert(out.b.error||'Error');await load()});document.getElementById('search').onclick=async()=>{const q=document.getElementById('q').value.trim();if(q.length<2)return;const out=await api('/api/messages/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:q,limit:60})});showMessages(out.b.messages)};document.getElementById('recent').onclick=async()=>{const out=await api('/api/messages/recent?limit=40');showMessages(out.b.messages)};const send=document.getElementById('send');if(send)send.onclick=async()=>{const st=document.getElementById('sendst');st.textContent='Enviando…';const out=await api('/api/output/send',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({to:document.getElementById('to').value,text:document.getElementById('msg').value,reason:'manual admin test',confirmedByUser:true})});st.className='status small '+(out.r.ok?'':'error');st.textContent=out.r.ok?'Enviado · '+(out.b.audit?.messageId||'ok'):(out.b.error||'Error')}}
async function load(){const out=await api('/api/state');if(!out.r.ok){app.innerHTML='<div class="card wide error">'+esc(out.b.error||'No se pudo cargar')+'</div>';return}render(out.b);const waiting=(out.b.accounts||[]).some(a=>['connecting','qr','reconnecting'].includes(a.runtime?.state));if(waiting)setTimeout(load,1500)}
load();
</script></body></html>`;
}
